# Generated by Django 3.0.2 on 2020-01-24 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200124_1025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examiner_score',
            old_name='users',
            new_name='user',
        ),
        migrations.AddField(
            model_name='examiner',
            name='exam_taken',
            field=models.BooleanField(default=False),
        ),
    ]
